In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [21]:
def sigmoid(z):
  return 1/(1 + np.exp(-z))
def train_logistic(X, y, lr=0.1, epochs=10000):
   m, n = X.shape
   w = np.zeros(n)
   b = 0.0
   for _ in range(epochs):
    z = np.dot(X, w) + b
    y_hat = sigmoid(z)
    dw = (1/m) * np.dot(X.T, (y_hat - y))
    db = (1/m) * np.sum(y_hat - y)
    w -= lr * dw
    b -= lr * db
    return w, b
def predict(X, w, b):
  probs = sigmoid(np.dot(X, w) + b)
  return (probs > 0.5).astype(int)

In [24]:
texts = [
# ---------------- HAM (0) ----------------
"Hi, are you free today",
"Please call me when you reach",
"Can you send the notes",
"I will be late by ten minutes",
"Lets meet after class",
"Your appointment is confirmed",
"Are you coming to college tomorrow",
"Please review the assignment",
"Thanks for your help",
"See you in the evening",
"What time is the meeting",
"I have shared the document",
"Please check your email",
"Call me after lunch",
"Can we reschedule to tomorrow",
"Happy birthday have a great day",
"I am in the library now",
"Dont forget the seminar at 2 pm",
"Please bring your ID card",
"Lets discuss the project",
# ---------------- SPAM (1) ----------------
"Congratulations you won a free prize",
"Claim your cash reward now",
"Urgent win money click here",
"You have been selected for a lottery",
"Free entry win a gift voucher",
"Get cheap loans apply now",
"Limited offer buy now",
"Click link to claim reward",
"Winner call now to receive money",
"Free mobile recharge offer",
"You are preapproved for credit card",
"Act now to get your bonus",
"Exclusive deal limited time offer",
"Earn money from home quickly",
"Your account will be blocked click to verify",
"Lowest price discount sale today",
"Get free coupons and rewards",
"Congratulations claim your jackpot",
"Win a brand new phone now",
"Hurry offer ends today click now"]

In [26]:
labels = [0]*20 + [1]*20 # 0=ham, 1=spam
y = np.array(labels, dtype=float)
print(y)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [27]:
X_train_texts, X_test_texts, y_train, y_test = train_test_split(texts, y, test_size=0.3,
random_state=42, stratify=y)

In [33]:
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(X_train_texts).toarray()
X_test = vectorizer.transform(X_test_texts).toarray()
print(X_train)
print(X_test)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 ...
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]
 [0 0 0 ... 0 0 1]]


In [30]:
w, b = train_logistic(X_train, y_train, lr=0.1, epochs=4000)
print(w,b)

[ 0.00178571 -0.00178571 -0.00178571  0.00178571  0.00178571 -0.00178571
  0.         -0.00178571  0.          0.00178571 -0.00178571  0.00178571
 -0.00178571  0.00178571 -0.00178571 -0.00357143 -0.00178571  0.
  0.00178571  0.00178571  0.00714286 -0.00178571  0.00178571  0.00178571
 -0.00178571  0.00178571  0.00178571 -0.00178571 -0.00178571 -0.00178571
  0.00178571  0.00178571  0.00178571 -0.00178571  0.00178571  0.00178571
 -0.00178571  0.00357143  0.00178571  0.00357143  0.00178571 -0.00178571
 -0.00178571 -0.00178571 -0.00178571  0.00178571 -0.00178571  0.00178571
  0.00178571 -0.00178571 -0.00357143 -0.00178571 -0.00178571 -0.00178571
 -0.00178571  0.00357143  0.00178571  0.00178571  0.00178571  0.00178571
 -0.00178571 -0.00357143 -0.00178571  0.00178571  0.00357143 -0.00178571
  0.00357143  0.00714286 -0.00357143 -0.00178571  0.00178571  0.00178571
 -0.00178571  0.00178571 -0.00178571  0.00178571  0.00178571  0.00178571
  0.00178571 -0.00178571  0.00178571 -0.00178571 -0.0017857

In [34]:
train_pred = predict(X_train, w, b)
test_pred = predict(X_test, w, b)
print(train_pred)
print(test_pred)

[1 1 0 1 0 1 0 0 1 1 1 1 0 0 0 0 0 1 1 0 1 1 1 0 0 1 0 0]
[1 0 0 0 0 1 1 0 0 1 1 0]


In [35]:
print("Train accuracy:", accuracy_score(y_train.astype(int), train_pred))
print("Test accuracy:", accuracy_score(y_test.astype(int), test_pred))

Train accuracy: 1.0
Test accuracy: 0.75
